export type Locale = 'en' | 'id';

export const defaultLocale: Locale = 'en';
export const locales: Locale[] = ['en', 'id'];

export const localeNames: Record<Locale, string> = {
  en: 'English',
  id: 'Bahasa Indonesia',
};

export interface Translations {
  // Navigation
  nav: {
    home: string;
    about: string;
    charts: string;
    readings: string;
    pricing: string;
    login: string;
    getStarted: string;
  };
  
  // Hero Section
  hero: {
    badge: string;
    title: string;
    subtitle: string;
    ctaPrimary: string;
    ctaSecondary: string;
    statsCharts: string;
    statsAccuracy: string;
    statsUsers: string;
  };
  
  // Features Section
  features: {
    title: string;
    subtitle: string;
    natalChart: {
      title: string;
      description: string;
    };
    aiReading: {
      title: string;
      description: string;
    };
    geodetic: {
      title: string;
      description: string;
    };
    relocation: {
      title: string;
      description: string;
    };
  };
  
  // Comparison Section
  comparison: {
    title: string;
    traditional: {
      label: string;
      points: string[];
    };
    astroai: {
      label: string;
      points: string[];
    };
  };
  
  // Blueprint Section
  blueprint: {
    title: string;
    subtitle: string;
    reject: {
      title: string;
      description: string;
    };
    accelerate: {
      title: string;
      description: string;
    };
    follow: {
      title: string;
      description: string;
    };
  };
  
  // Chart Form
  chartForm: {
    title: string;
    subtitle: string;
    birthDate: string;
    birthTime: string;
    location: string;
    latitude: string;
    longitude: string;
    timezone: string;
    houseSystem: string;
    calculate: string;
    generating: string;
  };
  
  // Footer
  footer: {
    tagline: string;
    madeWith: string;
    quote: string;
  };
}

export const translations: Record<Locale, Translations> = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      charts: 'My Charts',
      readings: 'Readings',
      pricing: 'Pricing',
      login: 'Sign In',
      getStarted: 'Get Started',
    },
    hero: {
      badge: 'Not Fortune Telling. It\'s About Purpose.',
      title: 'Discover Your Cosmic Blueprint',
      subtitle: 'Complete natal chart analysis with geodetic astrology. Date + Time + Location + Context = 95% accuracy.',
      ctaPrimary: 'Create Your Chart',
      ctaSecondary: 'Learn More',
      statsCharts: 'Charts Created',
      statsAccuracy: 'Accuracy Rate',
      statsUsers: 'Active Users',
    },
    features: {
      title: 'Why AstroAI?',
      subtitle: 'Data-driven astrological insights powered by Swiss Ephemeris',
      natalChart: {
        title: 'Natal Chart Calculation',
        description: 'Precise planetary positions with 0.001 arcsecond accuracy using Swiss Ephemeris.',
      },
      aiReading: {
        title: 'AI-Powered Readings',
        description: 'Personalized insights generated by GPT-4 & Claude, tailored to your unique context.',
      },
      geodetic: {
        title: 'Geodetic Astrology',
        description: 'Understand how your birth location and relocations affect your energy patterns.',
      },
      relocation: {
        title: 'Relocation Analysis',
        description: 'Discover which cities support your career, relationships, and personal growth.',
      },
    },
    comparison: {
      title: 'The Difference',
      traditional: {
        label: 'Traditional Horoscope',
        points: [
          'Based on birth month only',
          '12 types for 8 billion people',
          'Focus: fortune telling',
          '~20-30% accuracy',
        ],
      },
      astroai: {
        label: 'AstroAI',
        points: [
          'Date + Time + Location',
          'Unique for every individual',
          'Focus: purpose & patterns',
          '~70-95% accuracy',
        ],
      },
    },
    blueprint: {
      title: 'Chart = Blueprint, Not Destiny',
      subtitle: 'Your natal chart is a map of potential — not a prison.',
      reject: {
        title: 'You Can Reject',
        description: 'The chart shows tendencies, but you have free will to choose a different path.',
      },
      accelerate: {
        title: 'You Can Accelerate',
        description: 'Seeing patterns means you can work smarter, not just harder.',
      },
      follow: {
        title: 'You Can Follow',
        description: 'Flow with your natural energy — not fighting, but not surrendering either.',
      },
    },
    chartForm: {
      title: 'Create Your Chart',
      subtitle: 'Enter your birth details for a personalized analysis',
      birthDate: 'Birth Date',
      birthTime: 'Birth Time',
      location: 'Birth Location',
      latitude: 'Latitude',
      longitude: 'Longitude',
      timezone: 'Timezone',
      houseSystem: 'House System',
      calculate: 'Calculate Chart',
      generating: 'Generating...',
    },
    footer: {
      tagline: 'The stars incline, they do not compel.',
      madeWith: 'Made with cosmic curiosity',
      quote: 'Bintang-bintang membimbing, tidak memaksa.',
    },
  },
  
  id: {
    nav: {
      home: 'Beranda',
      about: 'Tentang',
      charts: 'Chart Saya',
      readings: 'Reading',
      pricing: 'Harga',
      login: 'Masuk',
      getStarted: 'Mulai Sekarang',
    },
    hero: {
      badge: 'Bukan Ramalan. Ini tentang Purpose.',
      title: 'Temukan Blueprint Kosmismu',
      subtitle: 'Analisis kartu natal lengkap dengan astrologi geodetik. Tanggal + Waktu + Lokasi + Konteks = 95% akurasi.',
      ctaPrimary: 'Buat Chart-mu',
      ctaSecondary: 'Pelajari Lebih',
      statsCharts: 'Chart Dibuat',
      statsAccuracy: 'Tingkat Akurasi',
      statsUsers: 'Pengguna Aktif',
    },
    features: {
      title: 'Kenapa AstroAI?',
      subtitle: 'Wawasan astrologi berbasis data dengan Swiss Ephemeris',
      natalChart: {
        title: 'Perhitungan Chart Natal',
        description: 'Posisi planet presisi dengan akurasi 0.001 arcsecond menggunakan Swiss Ephemeris.',
      },
      aiReading: {
        title: 'Reading Berbasis AI',
        description: 'Insight personal yang dihasilkan oleh GPT-4 & Claude, disesuaikan dengan konteks unikmu.',
      },
      geodetic: {
        title: 'Astrologi Geodetik',
        description: 'Memahami bagaimana lokasi lahir dan relokasi mempengaruhi pola energimu.',
      },
      relocation: {
        title: 'Analisis Relokasi',
        description: 'Temukan kota mana yang mendukung karir, hubungan, dan pertumbuhan pribadimu.',
      },
    },
    comparison: {
      title: 'Perbedaannya',
      traditional: {
        label: 'Horoskop Tradisional',
        points: [
          'Hanya berdasarkan bulan lahir',
          '12 tipe untuk 8 miliar orang',
          'Fokus: meramal',
          '~20-30% akurasi',
        ],
      },
      astroai: {
        label: 'AstroAI',
        points: [
          'Tanggal + Waktu + Lokasi',
          'Unik untuk setiap individu',
          'Fokus: purpose & pola',
          '~70-95% akurasi',
        ],
      },
    },
    blueprint: {
      title: 'Chart = Blueprint, Bukan Takdir',
      subtitle: 'Chart natalmu adalah peta potensi — bukan penjara.',
      reject: {
        title: 'Kamu Bisa Menolak',
        description: 'Chart menunjukkan kecenderungan, tapi kamu punya free will untuk memilih arah lain.',
      },
      accelerate: {
        title: 'Kamu Bisa Mempercepat',
        description: 'Melihat pola berarti kamu bisa bekerja lebih pintar, bukan cuma keras.',
      },
      follow: {
        title: 'Kamu Bisa Mengikuti',
        description: 'Flow dengan energi alamimu — bukan melawan, tapi juga bukan pasrah.',
      },
    },
    chartForm: {
      title: 'Buat Chart-mu',
      subtitle: 'Masukkan detail kelahiran untuk analisis personal',
      birthDate: 'Tanggal Lahir',
      birthTime: 'Waktu Lahir',
      location: 'Lokasi Lahir',
      latitude: 'Latitude',
      longitude: 'Longitude',
      timezone: 'Zona Waktu',
      houseSystem: 'Sistem House',
      calculate: 'Hitung Chart',
      generating: 'Menghitung...',
    },
    footer: {
      tagline: 'Bintang-bintang membimbing, tidak memaksa.',
      madeWith: 'Dibuat dengan rasa ingin tahu kosmis',
      quote: 'The stars incline, they do not compel.',
    },
  },
};

export function getTranslations(locale: Locale): Translations {
  return translations[locale] || translations[defaultLocale];
}

export function getLocaleFromPath(pathname: string): Locale {
  const locale = pathname.split('/')[1] as Locale;
  if (locales.includes(locale)) {
    return locale;
  }
  return defaultLocale;
}
